### ISSUE TITLE
mvvm구조 고민

### ISSUE THREAD

**Issue by modooJH** [zzikbu/PetDays#5]
현재 코드도 잘 작성되었지만 mvvm 구조로 만들어보는 것도 좋은 공부가 될 것 같습니다. 
질문 주셨던 main에 대해서는 강의시간에 다시 얘기해 보면 좋겠습니다. 
특별히 지적할 만한 사항은 없었습니다. 

## w_avatar.dart

url이 형태는 잘 갖추지만, 실제로 잘못되었을경우 profile.png가 나오지 않음.  
error builder 형태를 취하던지 url이 실제로 이미지를 가져오는지 check하면 더 좋겠음. 

## diary_detail_screen.dart

- mvvm 구현을 원한다면 viewmodel을 만들고 그곳에서 필요한 dependency를 모두 갖고 있는게 좋겠음. context.read<FeedProvider>()  
    context.watch<DiaryState>()  
    context.watch<LikeState>()  
    context.watch<FeedState>()  
    context.read<LikeProvider>()  
    현재는 screen에서 많은 provider와 state에 종속되고 있음.  이를 하나의 상태로 통합해서 관리하는게 더 직관적일것 같음. 

- screen에 type이 정의되어 있음. 파일로 분리 필요.

**Comment by zzikbu** [comment]
감사합니다 !
